# Generated by Django 3.0.7 on 2020-06-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200614_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='work_name',
        ),
    ]
