# Generated by Django 3.0.7 on 2020-06-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200628_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
    ]
