# Generated by Django 3.0.7 on 2020-06-14 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_work_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Task'),
        ),
    ]
