# Generated by Django 3.0.7 on 2020-06-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_work_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='work_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
    ]
