# Generated by Django 3.0.7 on 2020-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200925_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='haveDeadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default='%2020-%09-%25 %14:%Sep'),
        ),
    ]
