# Generated by Django 3.0.7 on 2020-06-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200614_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
            preserve_default=False,
        ),
    ]
